#CFLAGS=--std=c++0x -W -Wall -Wno-sign-compare -O2 -s -pipe -mmmx -msse -msse2 -msse3
CFLAGS=--std=c++11 -pthread -W -Wall -Wno-sign-compare -mmmx -msse -msse2 -msse3 -O3 

all:
	g++ $(CFLAGS) SOL.cpp -o a.out
